services:
  mysql:
    image: mysql:8.0
    container_name: sportify-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: sportify_db
      MYSQL_USER: sportify_user
      MYSQL_PASSWORD: sportify_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - sportify-network

  # Uncomment the section below if you want to containerize the Spring Boot application as well
  sportify-app:
    build: .
    container_name: sportify-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sportify-network

volumes:
  mysql_data:

networks:
  sportify-network:
    driver: bridge